#LLAMADAS
#CREACIÓN DE TABLAS
USE ODS;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS ODS_HC_LLAMADAS;

#NO HAY FORMA DE RELACIONARLO CON 
#CLIENTES, Y SUS NUMEROS DE TELEFONO
#PERO YA LOS DEJAMOS PREPARADOS EN EL MODELO
#PODRÍAMOS RELACIONARLO CON UN CLIENTE 999999 DESCONOCIDO
#PERO CREO QUE AHORA NO APORTA VALOR ALGUNO
CREATE TABLE ODS_HC_LLAMADAS
(ID_LLAMADA INT NOT NULL AUTO_INCREMENT PRIMARY KEY
, ID_CLIENTE INT NOT NULL
, TELEFONO_INTERNO BIGINT (20)
, TELEFONO_CLIENTE_PRINCIPAL BIGINT (20)
, TELEFONO_CLIENTE_ALTERNATIVO BIGINT (20)
, FECHA_HORA_INICIO_LLAMADA DATETIME
, FECHA_HORA_FIN_LLAMADA DATETIME
, ID_SERVICIO INT(10) UNSIGNED NOT NULL
, TRANSFERIDA CHAR(1)
, ID_AGENTE INT(10) UNSIGNED NOT NULL
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_SERVICIOS;

CREATE TABLE ODS_DM_SERVICIOS
(ID_SERVICIO INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY
, DE_SERVICIO VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_AGENTES;
CREATE TABLE ODS_DM_AGENTES
(ID_AGENTE INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY
, NICK_AGENTE VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

#CREACIÓN DE FK
#NO CREAMOS LA FK CON CLIENTES AL NO TENER AÚN POSIBILIDAD
#DE RELACIONARLO

USE ODS;

ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_llam_svc_idx (ID_SERVICIO ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_llam_svc_idx FOREIGN KEY (ID_SERVICIO)
    REFERENCES ODS_DM_SERVICIOS(ID_SERVICIO);

ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_llam_agent_idx (ID_AGENTE ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_agent_svc_idx FOREIGN KEY (ID_AGENTE)
    REFERENCES ODS_DM_AGENTES(ID_AGENTE);

#POBLAMOS EL MODELO
#DIMENSION SERVICIOS
INSERT INTO ODS_DM_SERVICIOS (DE_SERVICIO, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(SERVICE)) DE_SERVICIO
, NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR
WHERE TRIM(SERVICE)<>'';
INSERT INTO ODS_DM_SERVICIOS VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_SERVICIOS VALUES (98, 'NO APLICA', NOW(), NOW());    
COMMIT;
ANALYZE TABLE ODS_DM_SERVICIOS;

#DIMENSION AGENTES
INSERT INTO ODS_DM_AGENTES (NICK_AGENTE, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(AGENT)) NICK_AGENTE
, NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR
WHERE TRIM(AGENT)<>'';
INSERT INTO ODS_DM_AGENTES VALUES (99999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_AGENTES VALUES (99998, 'NO APLICA', NOW(), NOW());    
COMMIT;
ANALYZE TABLE ODS_DM_AGENTES;

#TABLA DE HECHOS LLAMADAS
#NO HAY FORMA DE RELACIONARLO CON 
#CLIENTES, Y SUS NUMEROS DE TELEFONO
#PERO YA LOS DEJAMOS PREPARADOS EN EL MODELO
INSERT INTO ODS_HC_LLAMADAS
(ID_CLIENTE
, TELEFONO_INTERNO
, TELEFONO_CLIENTE_PRINCIPAL
, TELEFONO_CLIENTE_ALTERNATIVO
, FECHA_HORA_INICIO_LLAMADA
, FECHA_HORA_FIN_LLAMADA
, ID_SERVICIO
, TRANSFERIDA
, ID_AGENTE
, FC_INSERT
, FC_MODIFICACION)
SELECT 999999999
, CASE WHEN TRIM(PHONE_NUMBER)<>'' THEN REPLACE(PHONE_NUMBER,'-','') ELSE 9999999999 END TELEFONO_INTERNO
, 9999999999
, 9999999999
, CASE WHEN TRIM(START_DATETIME)<>'' THEN STR_TO_DATE(LEFT(START_DATETIME, 19),  '%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999 00:00:00','%d/%m/%Y  %H:%i:%s') END FECHA_HORA_INICIO_LLAMADA
, CASE WHEN TRIM(END_DATETIME)<>'' THEN STR_TO_DATE(LEFT(END_DATETIME, 19), '%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999 00:00:00','%d/%m/%Y  %H:%i:%s') END FECHA_HORA_FIN_LLAMADA
, CASE WHEN OODS.ID_SERVICIO<>'' THEN OODS.ID_SERVICIO ELSE 99 END ID_SERVICIO
, CASE WHEN UPPER(TRIM(SSCI.FLG_TRANSFER))='TRUE' THEN('S') ELSE 'N' END TRANSFERIDA
, CASE WHEN OODA.ID_AGENTE<>'' THEN OODA.ID_AGENTE ELSE 99999 END ID_AGENTE
, NOW()
, NOW()
FROM STAGE.STG_CONTACTOS_IVR SSCI
LEFT JOIN ODS.ODS_DM_SERVICIOS OODS ON (OODS.DE_SERVICIO=UPPER(TRIM(SSCI.SERVICE)))
LEFT JOIN ODS.ODS_DM_AGENTES OODA ON (OODA.NICK_AGENTE=UPPER(TRIM(SSCI.AGENT)));

COMMIT;

SET FOREIGN_KEY_CHECKS=1;
